
rm(list = ls()) # clear out previous data 
dev.off()       # close all previous plots
cat("\014")     # clear console of previous output

library(eeptools)
library("tidyr")
library("dplyr")

#------------------------------------------------------------

setwd("/Users/me/Documents/Doerr Lab/ShyA manuscript/R data/Clists")
filelist <- list.files()
filelist

# making a dataframe called datafull because we can't rbind something onto nothing
fl <- filelist[1]
load(fl)
datafull <- data
rm(data)

for (i in 2:length(filelist)){
  fl <- filelist[i]
  cat(fl,"\n")
  load(fl)
  datafull <- rbind(datafull, data)
  rm(data)
}

anyDuplicated(datafull)

table(datafull$strain, datafull$position)
table(datafull$strain, datafull$date)
table(datafull$strain, datafull$medium)

Empty_1 <- filter(datafull, strain == "Empty" & position == 1)
table(Empty_1$date)
ShyA_1 <- filter(datafull, strain == "ShyA" & position == 1)
table(ShyA_1$date)

# trimming spaces from date
datafull$date <- trimws(datafull$date)
table(datafull$strain, datafull$date)

# now that we're done with rbind, we don't need datafull anymore
# so we can rename it data
data <- datafull
rm(datafull)


isid(data, vars = c("strain", "position", "date", "medium", "cellid"), verbose = TRUE)


# DELETING CELLS WITH ERRORS
# checking to see if any particular strains are more prone to errors
print("Percent of MATLAB errors by strain (in TRUE)")
prop.table(table(data$strain,data$error_MATLAB),margin=1)

print("Percent of zero length growth errors by strain (in TRUE)")
prop.table(table(data$strain,data$error_nogrowthL), margin=1)

print("Percent of zero width growth errors by strain (in TRUE)")
prop.table(table(data$strain,data$error_nogrowthW), margin=1)

# nope, this is probably just from having more cells :)

# which cells will be lost for which reason?
print("Percent of MATLAB errors by birth frame (in TRUE)")
table(data$birthframe, data$error_MATLAB)
prop.table(table(data$birthframe, data$error_MATLAB),margin = 1)

print("Percent of zero length growth errors by birth frame (in TRUE)")
table(data$birthframe, data$error_nogrowthL)
prop.table(table(data$birthframe, data$error_nogrowthL),margin = 1)

print("Percent of zero width growth errors by birth frame (in TRUE)")
table(data$birthframe, data$error_nogrowthW)
prop.table(table(data$birthframe, data$error_nogrowthW),margin = 1)
# it's ok that all the cells born in frame 30 are thrown out

# checking the length values for cells that don't have any errors
# (either errors generated by MATLAB or errors from zero growth)
# purpose of this is to identify any cells that I need to look at manually
data_noerror <- data[(data$error_MATLAB==0 & data$error_nogrowthL==0 & data$error_nogrowthW==0
              & data$error_nogrowthA==0),]
hist(data_noerror$lengthbirth)

# looking at the largest length values
data_noerror_sort <- data_noerror[order(-data_noerror$lengthbirth),]
data_noerror_sort[1:10,c(1,3,5,6,7,8,9,10,11,12)]

data_noerror_sort <- data_noerror[order(-data_noerror$lengthdeath),]
data_noerror_sort[1:10,c(1,3,5,6,7,8,9,10,11,12)]

# looking at the largest width values
data_noerror_sort <- data_noerror[order(-data_noerror$widthbirth),]
data_noerror_sort[1:10,c(1,3,5,6,7,8,9,10,11,12)]

data_noerror_sort <- data_noerror[order(-data_noerror$widthdeath),]
data_noerror_sort[1:10,c(1,3,5,6,7,8,9,10,11,12)]

# looking at the largest area values
data_noerror_sort <- data_noerror[order(-data_noerror$areabirth),]
data_noerror_sort[1:10,c(1,3,5,6,7,8,9,10,11,12)]

data_noerror_sort <- data_noerror[order(-data_noerror$areadeath),]
data_noerror_sort[1:10,c(1,3,5,6,7,8,9,10,11,12)]


# at this point I should manually go through and look up just these few cells that seem weird


# weeding out cells that have errors
rm(data)
rm(data_noerror_sort)
data <- data_noerror
rm(data_noerror)


# adding a column to show whether or not each cell divided
data$division <- !is.na(data$daughter1)
prop.table(table(data$strain,data$division), margin = 1)

# adding a column for cell age at division
data$division_age <- data$age 
data$division_age[is.na(data$daughter1)] <- NA

# making a column with full strain names so they appear this way on the X axis
data$full_strain_name <- with(data, ifelse(strain == 'E103A', 'ΔshyA pFIS-shyA E103A',
                                           ifelse(strain == 'WT', 'N16961',
                                                  ifelse(strain == 'ShyA', 'ΔshyA pFIS-shyA',
                                                         ifelse(strain == 'G81A', 'ΔshyA pFIS-shyA G81A',
                                                                ifelse(strain == 'I87A', 'ΔshyA pFIS-shyA I87A',
                                                                       'ΔshyA pFIS-empty'))))))

# ordering the strains according to estimated ShyA activity level
data$full_strain_name <- factor(data$full_strain_name,  levels = c("ΔshyA pFIS-shyA E103A",
                                                                   "N16961",
                                                                   "ΔshyA pFIS-shyA",
                                                                   "ΔshyA pFIS-shyA G81A",
                                                                   "ΔshyA pFIS-shyA I87A",
                                                                   "ΔshyA pFIS-empty"))




# reordering columns
data <- data[, c("strain",
                 "full_strain_name", 
                 "position", 
                 "date", 
                 "medium",                  
                 "cellid", 
                 "birthframe",
                 "deathframe",
                 "age",
                 "mother", 
                 "daughter1",
                 "daughter2",
                 "division", 
                 "division_age", 
                 "lengthbirth",             
                 "lengthdeath",
                 "widthbirth", 
                 "widthdeath", 
                 "areabirth",
                 "areadeath",
                 "ratiobirth",
                 "ratiodeath",
                 "maxwidth")]                                 
                                    

# making sure there are no duplicates
anyDuplicated(data)
# no duplicates

# Saving all clists as one giant dataframe called AllClists.RData
setwd("/Users/me/Documents/Doerr Lab/ShyA manuscript/R data")
save(data, file = "AllClists.RData")

